services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Node.js
      - "5001:5001"  # Python
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    networks:
      - backend_network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    ports:
      - "8080:8080"  
      - "50000:50000" 
    volumes:
      - jenkins_home:/var/jenkins_home 
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false 
    restart: unless-stopped  

  # sonarqube:
  #   image: sonarqube:latest
  #   container_name: sonarqube
  #   ports:
  #     - "9000:9000"  # Puerto donde SonarQube estará disponible
  #   environment:
  #     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
  #     - SONARQUBE_JDBC_USERNAME=sonar
  #     - SONARQUBE_JDBC_PASSWORD=sonar
  #   volumes:
  #     - sonarqube_data:/opt/sonarqube/data
  #     - sonarqube_extensions:/opt/sonarqube/extensions
  #     - sonarqube_logs:/opt/sonarqube/logs
  #   depends_on:
  #     - sonar-db
  #   networks:
  #     - sonarqube_network

  # sonar-db:
  #   image: postgres:latest
  #   container_name: sonar-db
  #   environment:
  #     POSTGRES_USER: sonar
  #     POSTGRES_PASSWORD: sonar
  #     POSTGRES_DB: sonar
  #   volumes:
  #     - sonar_db_data:/var/lib/postgresql/data
  #   networks:
  #     - sonarqube_network

  # sonar-scanner:
  #   image: sonarsource/sonar-scanner-cli:latest
  #   container_name: sonar-scanner
  #   environment:
  #     - SONAR_HOST_URL=http://127.0.0.1:9000
  #     - SONAR_PROJECT_KEY=my_project_key
  #     - SONAR_PROJECT_NAME=My Project
  #     - SONAR_PROJECT_VERSION=1.0
  #   command: >
  #     sonar-scanner -Dsonar.sources=/app/src
  #   depends_on:
  #     - sonarqube
  #   networks:
  #     - sonarqube_network

networks:
  backend_network:
    driver: bridge
#   sonarqube_network:
#     driver: bridge
volumes:
  jenkins_home: 
#   sonarqube_data:
#   sonarqube_extensions:
#   sonarqube_logs:
#   sonar_db_data:
