name: CI/CD Pipeline for Node.js and Python with Docker Compose

on:
  push:
    branches:
      - develop  
  pull_request:
    branches:
      - develop  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Clone
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker Define
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # build docker image
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            your-dockerhub-username/node-app:latest
            your-dockerhub-username/python-app:latest

      # upload services
      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
