name: CI/CD Pipeline for Node.js and Python with Docker Compose

on:
  push:
    branches:
      - main  # Ejecutar en cada push a la rama principal
  pull_request:
    branches:
      - main  # También ejecutar en pull requests

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 3: Autenticarse en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 4: Construir imágenes Docker
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            your-dockerhub-username/node-app:latest
            your-dockerhub-username/python-app:latest

      # Paso 5: Levantar servicios con Docker Compose
      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
